apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |-
    grafana:
      adminUser: admin
      adminPassword: prom-operator

      service:
        type: ClusterIP

    prometheus:
      prometheusSpec:
        retention: 2d

    alertmanager:
      enabled: false
